resolver: lts-21.4

extra-deps:
- ../../../accelerate
- ../../../accelerate-llvm/accelerate-llvm
- ../../../accelerate-llvm/accelerate-llvm-native

# - github: acceleratehs/accelerate
#   commit: 5ceb2da5d9ddc4ea0a5705d46bf4de9321ba17da
# - github: acceleratehs/accelerate-llvm
#   commit: 2b5d69448557e89002c0179ea1aaf59bb757a6e3
#   subdirs: 
#     - accelerate-llvm
#     - accelerate-llvm-native
#   - accelerate-llvm-ptx
# - cuda-0.11.0.1
# - nvvm-0.10.0.1
- github: llvm-hs/llvm-hs
  commit: e4b3cfa47e72f094ab109884f18acfc666b0fb7d  # llvm-15
  subdirs:
    - llvm-hs
    - llvm-hs-pure
